### ISSUE TITLE
[BUG] `matplotlib` is required via `stack.py`, but not listed in `install-requires`

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/hist#352]
**Describe the bug**

When importing `hist` into an environment without `matplotlib`, a `ModuleNotFoundError` is raised. This occurs because `__init__.py` imports `stack.py`, and `stack.py` catches and re-raises the exception.

**Steps to reproduce**

```bash
$ pipx run --spec "hist==2.5.2" python -c "import hist"   
Hist requires mplhep to plot, either install hist[plot] or mplhep
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/angus/.local/pipx/.cache/6ebab805ae1bce3/lib/python3.9/site-packages/hist/__init__.py", line 15, in <module>
    from .stack import Stack
  File "/home/angus/.local/pipx/.cache/6ebab805ae1bce3/lib/python3.9/site-packages/hist/stack.py", line 15, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
```

**Desired behaviour**
I would prefer for `matplotlib` not to be a required dependency (i.e. honour the existing `extras-require` section)

**Comment by agoose77** [comment]
Thanks for the quick fix!
